#!/bin/sh
echo "*********************  Testing reposync *******************************"
echo "**** repoclosure -n --urls"
python reposync.py -n --urls 
echo "*************************************************************************"

