#!/bin/sh
echo "*********************  Testing repotrack *******************************"
echo "**** repotrack --urls yum"
rm yum*.rpm
python repotrack.py --urls yum
echo "*************************************************************************"

