#!/bin/sh
echo "*********************  Testing repoclosure *******************************"
echo "**** repoclosure -n"
python repoclosure.py -n 
echo "*************************************************************************"

