.\" repodiff
.TH "repodiff" "1" "2008 October 21" "James Antill" ""
.SH "NAME"
repodiff
.SH "SYNOPSIS"
\fBrepodiff\fP --old=old_repo_baseurl --new=new_repo_baseurl
.SH "DESCRIPTION"
.PP 
\fBrepodiff\fP is a program which will list differences between two sets of 
repositories.  \fBNote\fP that by default only source packages are compared.
.PP 
.SH "GENERAL OPTIONS"
.IP "\fB\-\-old, -o\fP"
Add a repo. as an old repo.
.IP "\fB\-\-new, -n\fP"
Add a repo. as an new repo.
.IP "\fB\-\-archlist, -a\fP"
Add architectures to change the default from just comparing source packages.
.IP "\fB\-\-size, -s\fP"
Ouput additional data about the size of the changes.
.SH "EXAMPLES"
.IP "Compare source pkgs in two local repos:"
\fBrepodiff --old=/tmp/repo-old --new=/tmp/repo-new\fP
.IP "Compare x86_64 binary pkgs in two remote repos, and two local one:"
\fBrepodiff -a x86_64,i386,noarch,src --old=http://example.com/repo1-old --old=/tmp/repo-old --new=http://example.com/repo1-new --new=/tmp/repo-new\fP
.PP 

.SH "SEE ALSO"
.nf
.I yum.conf (5)
http://yum-utils.baseurl.org/
http://yum.baseurl.org/
.fi 

.PP 
.SH "AUTHORS"
.nf 
See the Authors file included with this program.
.fi 

.PP 
.SH "BUGS"
There of course aren't any bugs, but if you find any, they should be sent
to the mailing list: yum@lists.baseurl.org or filed in trac.
.fi
