.\" reposync
.TH "reposync" "1" "2007 Apr 27" "" ""
.SH "NAME"
reposync - synchronize yum repositories to a local directory
.SH "SYNOPSIS"
\fBreposync\fP [options]
.SH "DESCRIPTION"
\fBreposync\fP is used to synchronize a remote yum repository to a local
directory, using yum to retrieve the packages.
.SH "OPTIONS"
.IP "\fB\-h, \-\-help\fP"
Display a help message, and then quit.
.IP "\fB\-c CONFIG, \-\-config=CONFIG\fP"
Config file to use (defaults to /etc/yum.conf).
.IP "\fB\-a ARCH, \-\-arch=ARCH\fP"
Act as if running the specified arch (default: current arch, note: does
not override $releasever).
.IP "\fB\-r REPOID, \-\-repoid=REPOID\fP"
Specify repo ids to query, can be specified multiple times (default is
all enabled).
.IP "\fB\-t, \-\-tempcache\fP"
Use a temp dir for storing/accessing yum-cache.
.IP "\fB\-p DESTDIR, \-\-download_path=DESTDIR\fP"
Path to download packages to: defaults to current directory.
.IP "\fB\-g, \-\-gpgcheck\fP"
Remove packages that fail GPG signature checking after downloading.
.IP "\fB\-u, \-\-urls\fP"
Just list urls of what would be downloaded, don't download.
.IP "\fB\-n, \-\-newest-only\fP"
Download only newest packages per-repo.
.IP "\fB\-q, \-\-quiet\fP"
Output as little information as possible.
.SH "EXAMPLES"
.IP "Sync all packages from the 'updates' repo to the current directory:"
\fB reposync --repoid=updates\fP
.IP "Sync only the newest packages from the 'updates' repo to the current directory:"
\fB reposync -n --repoid=updates\fP
.IP "Sync packages from the 'updates' and 'extras' repos to the current directory:"
\fB reposync --repoid=updates --repoid=extras\fP
.IP "Sync all packages from the 'updates' repo to the \fBrepos\fP directory:"
\fB reposync -p repos --repoid=updates\fP
.SH "FILES"
\fBreposync\fP uses the yum libraries for retrieving information and
packages. If no configuration file is specified, the default yum
configuration will be used.
.PP
.nf 
/etc/yum.conf
/etc/yum/repos.d/
.fi
.SH "SEE ALSO"
.nf
.I yum.conf (5)
http://linux.duke.edu/yum/
.fi
.SH "AUTHORS"
.nf 
See the Authors file included with this program.
.fi
