.\" PROCESS THIS FILE WITH
.\" groff -man -Tascii yum-versionlock.1
.\"
.TH YUM-VERSIONLOCK 1 "28 December 2009" "" "User Manuals"
.SH NAME
yum-versionlock - Version lock rpm packages
.SH SYNOPSIS
.B yum-versionlock
[ package-name [ package-name]] ...
.SH DESCRIPTION
.BR yum-versionlock(1)
is a Yum plugin that takes a set of name/versions for packages and excludes all
other versions of those packages (including optionally following obsoletes).
This allows you to protect packages from being updated by newer versions.
.PP
The plugin provides a command "versionlock" which allows you to view and edit
the list of locked packages easily.
.br
.I  \fR yum versionlock add <package-wildcard>...
.PP
Add a versionlock for all of the packages in the rpmdb matching the given
wildcards.
.I  \fR yum versionlock exclude <package-wildcard>...
.PP
Add a exclude (within versionlock) for the latest versions of the
packages in the available repos. matching the given wildcards.
.I  \fR yum versionlock list
.PP
List the current versionlock entries.
.I  \fR yum versionlock delete <entry-wildcard>...
.PP
Remove any matching versionlock entries.
.I  \fR yum versionlock clear
.PP
Remove all versionlock entries.

.SH FILES
.I /etc/yum/pluginconf.d/versionlock.conf
.RS
The system wide configuration file. See
.BR yum-versionlock.conf(5)
for more information.
.RE
.I /etc/yum/pluginconf.d/versionlock.list
.RS
The default place to put package version lock information (one package and
version per. line). The file takes entries in the following format 
.BR EPOCH:NAME-VERSION-RELEASE.ARCH 
See 
.BR rpm(8) 
for more information on custom query formats. If the package does not have an EPOCH the number will default to 0.
.RE
.SH BUGS
There are of course no bugs, but should you find any, you should first
consult the FAQ section on http://yum.baseurl.org/wiki/Faq and if unsuccessful
in finding a resolution contact the mailing list: yum-devel@lists.baseurl.org.
To file a bug use http://bugzilla.redhat.com for Fedora/RHEL/Centos
related bugs and http://yum.baseurl.org/report for all other bugs.

.SH AVAILABILITY
yum-versionlock is available via:
.nf
# yum install yum-versionlock
.fi
.SH AUTHORS
Panu Matilainen <pmatilai@laiskiainen.org>
.br
James Antill <james@and.org>
.br
Documentation modified by:
.br
Gerhardus Geldenhuis <gerhardus.geldenhuis@gmail.com>
.SH "SEE ALSO"
.BR yum(1)
