.TH "yum\-ovl" "1" "September 2015" "Red Hat" "User Manual"
.
.SH "NAME"
yum\-ovl \- Performs an initial copy\-up of yum(8) package database\.
.
.SH "OPTIONS"
\fB\-d\fR \fIdebug\-level\fR If debug level is \fI2\fR and more, print out the number of files copied up from the lower layer
.
.SH "FILES"
\fI/usr/lib/yum\-plugins/ovl\.py\fR Plugin itself
.
.P
\fI/etc/yum/pluginconf\.d/ovl\.conf\fR Configuration file allowing to enable/disable the plugin
.
.SH "AUTHOR"
Pavel Odvody \fIpodvody@redhat\.com\fR
.
.SH "LICENSE"
2015, Red Hat, Licensed under GPLv2+
.
.SH "SEE ALSO"
yum(1) yum(8)
