.\" yum-debug-dump
.TH "yum-debug-dump" "1" "2008 Apr 28" "Seth Vidal" ""
.SH "NAME"
yum-debug-dump
.SH "SYNOPSIS"
\fByum-debug-dump\fP
.SH "DESCRIPTION"
.PP 
\fByum-debug-dump\fP is a program which creates a gzipped file containing a
lot of information useful to developers trying to debug a problem.
.PP
By default it will output a file to the current working directory named
yum_debug_dump.txt.gz. This file contains no private information but does
contain a complete list of all packages you have installed, all packages
available in any repository, important configuration and system information.
You can view this file using the 'zless' command.
.PP 
.SH "FILES"
As yum-debug-dump uses YUM libraries for retrieving all the information, it
relies on YUM configuration for its default values like which repositories
to use. Consult YUM documentation for details:
.PP
.nf 
/etc/yum.conf
/etc/yum/repos.d/
/var/cache/yum/
.fi 

.PP 
.SH "SEE ALSO"
.nf
.I yum.conf (5)
http://yum.baseurl.org/
.fi 

.PP 
.SH "AUTHORS"
.nf 
See the Authors file included with this program.
.fi 

.PP 
.SH "BUGS"
There of course aren't any bugs, but if you find any, they should be sent
to the mailing list: yum-devel@lists.baseurl.org or filed in trac.
.fi
